const a = "3+";
const b = "3b+";
const c = "FEn";
const d = "FE ";
const pattern = /^[a-zA-Z]+$/;
/^[a-z|A-Z]+$/;
console.log(pattern.test(a));
console.log(pattern.test(b));
console.log(pattern.test(c));
console.log(pattern.test(d));
